### PR TITLE
Create Docker container using a Dockerfile from NGINX

### PR DESCRIPTION
**Pull request by jtgans**
Hey Vernon,

This change should allow you to put up more mirrors of the repository yourself more frequently and across the web, helping with the reduction in downtime for the site sometimes. Hopefully this gives you a leg up in hosting the site. Your collection of these files and information together has been quite helpful to others, and I thought I would contribute back by providing another way for you to scale the site.

Thanks! :D

### CODE REVIEW

**Comment by pcdosretro** [comment]
Mirrors of my website are expressly forbidden, pull request closed.

**Comment by jtgans** [comment]
Ah, that's unfortunate, and apologies -- I didn't realize making a mirror of this was forbidden. Is there any particular reason why? Your site is really quite helpful to others.

**Comment by pcdosretro** [comment]
I take it you are working with geneb who made an unauthorized copy of my website on his and you are part of some sort of revenge plot. If not then sorry but it does seem like an incredible coincidence. I'm very displeased about this and really don't understand why anyone would copy someone else's work with permission.

**Comment by jtgans** [comment]
I have no idea who geneb is -- I just thought it would be helpful to provide a way for you to spin up a site since I have used your site as a reference in the past on my own personal projects. The source code for your site is on Github, an open collaborative site designed to allow for patches to be sent. All I did was create a patch and send it to you. My apologies if that was against your wishes.

**Pull request closed without merging**
